### ISSUE TITLE
FiveM version failing to load

### ISSUE THREAD

**Issue by TaaVetP** [Jesper-Hustad/NoPixel-minigame#14]
![image](https://user-images.githubusercontent.com/81780337/120103238-578b6200-c157-11eb-95b3-d624eceb460b.png)

**Comment by Jesper-Hustad** [comment]
Error occurs when FiveM tries to run `openHack()` in `hacking/client/main lua`

**Comment by Jesper-Hustad** [comment]
@RealDebugg could you take a look at this issue?

**Comment by Jesper-Hustad** [comment]
@TaaVetP have you looked at the code? What do you think the issue is, and could you be able to fix it?

**Comment by RealDebugg** [comment]
Working on a new pull request :)
 I'll update you

**Comment by RealDebugg** [comment]
I've posted a pr, with a fixed version. Not sure why I formatted the function statements incorrectly. But hopefully this should fix all of the errors. Either wait until Jesper merges the changes, or download the fix here: https://github.com/Jesper-Hustad/NoPixel-minigame/pull/15/commits/43bf727cde34168203a105757e77a6a2d30e5bce

**Comment by Jesper-Hustad** [comment]
Alright, merged!
Thanks @RealDebugg you da real MVP

**Comment by RealDebugg** [comment]
😄

**Comment by Jesper-Hustad** [comment]
Getting a new error:  
![image](https://user-images.githubusercontent.com/81780337/120117137-6cd2b180-c194-11eb-9322-0a219b9ed6bc.png)

**Comment by RealDebugg** [comment]
I'll send a pr tommorow :)

**Comment by Jesper-Hustad** [comment]
Thank you very much, appreciate the help!

**Comment by RealDebugg** [comment]
Opened pr

**Comment by Jesper-Hustad** [comment]
@TaaVetP Can you test if it works now?

**Comment by TaaVetP** [comment]
nope :( 
![image](https://user-images.githubusercontent.com/81780337/120235467-c0abcc00-c262-11eb-9f2a-1c89fdb26823.png)

**Comment by RealDebugg** [comment]
I feel as if the "FiveM" js is crashing with the js used in the generell code for the ui. I'll do some more looking into this, but keep in mind that I wont be able to do any testing myself until the weekend. :)

**Comment by TaaVetP** [comment]
ok :(

**Comment by RealDebugg** [comment]
new pr

**Comment by Jesper-Hustad** [comment]
I was just doing the exact changes you made 😄 so i just commited it.
Also removed the JQuery code.

**Comment by RealDebugg** [comment]
😄 perfect haha. Yeah its similar but hopefully, just copied that straight off of the fivem docs. Weird thing is the js code I used in earlier pushes is code that works on other scripts I've made 🤷‍♂️

**Comment by RealDebugg** [comment]
Recommend using "===" in if statements where variable conversion isn't required :)

**Comment by RealDebugg** [comment]
window.addEventListener('message', function(event){
if (event.data.action === "open") {
start();
$(".bg").classList.remove('hidden'); //jquery
});

**Comment by Jesper-Hustad** [comment]
> Recommend using "===" in if statements where variable conversion isn't required :)

When i write html in IntelliJ it keeps telling me that to.

**Comment by RealDebugg** [comment]
You would have to update the code in the start function as well to make it hide when its supposed to

**Comment by RealDebugg** [comment]
Yeah it wont affect much but its unnecessary work

**Comment by Jesper-Hustad** [comment]
> $(".bg").classList.remove('hidden'); //jquery
That is not JQuery
The dollar sign is defined in helper.js as `$ = name => document.querySelector(name)`
So it just uses the built in QuerySelector. Just quicker than always writing document.querySelector you know?

**Comment by RealDebugg** [comment]
Ooooooooh yeah haha. Thats really smart

**Comment by RealDebugg** [comment]
But yeah, update the jquery in the start function I added then

**Comment by RealDebugg** [comment]
You're already ahead of me haha

**Comment by huyaks** [comment]
I am having issues regarding the hack actually opening when triggering the event TriggerEvent('open:minigame')

All the sounds play but the UI does not appear. Any idea why?

**Comment by FjamZoo** [comment]
https://gyazo.com/252fc4d471987d7a8887597b2ce263aa

Looks like the game UI is underneath the game?

**Comment by Jesper-Hustad** [comment]
> https://gyazo.com/252fc4d471987d7a8887597b2ce263aa
> 
> Looks like the game UI is underneath the game?

I don't have access to GTA or FiveM.
Really appreciate if you have access to troubleshoot and debug a bit.
Will happily pull you changes if you can fix it.

Thanks for helping!

**Comment by Jesper-Hustad** [comment]
> I am having issues regarding the hack actually opening when triggering the event TriggerEvent('open:minigame')
> 
> All the sounds play but the UI does not appear. Any idea why?
> 
> ![image](https://user-images.githubusercontent.com/78702172/120248079-c34af900-c243-11eb-85c5-3f4197990d86.png)

This should be fixed now, try pulling updates.

**Comment by Jesper-Hustad** [comment]
Deleted comments because issue was getting really long

**Comment by FjamZoo** [comment]
Couldn't find the solution since I am not that good at HTML, CSS or JS. But it's diffently something todo with overlapping. All the sounds plays, there's a cursor. Even when the hack fails (Which it does since I can't see) I get the notification "Hack Failed" so yeah not sure what's causing this.

**Comment by huyaks** [comment]
Still getting the same issue as before, for some reason can't even get the hack to open.

**Comment by TaaVetP** [comment]
[jquery-ui.min.zip](https://github.com/Jesper-Hustad/NoPixel-minigame/files/6573504/jquery-ui.min.zip)
dont you need this for jquery?

**Comment by dec7092** [comment]
i have managed to get the hacking open but when trying to complete the hack it will give the correct numbers 1-4, but then when trying to complete the hack it will show random numbers up to 8 when this was not on the previous screen
![ads](https://user-images.githubusercontent.com/70960666/120274522-e1e2db80-c2a7-11eb-874a-08082d6f51f0.png)

**Comment by Jesper-Hustad** [comment]
[jquery-ui.min.zip](https://github.com/Jesper-Hustad/NoPixel-minigame/files/6573504/jquery-ui.min.zip)
> dont you need this for jquery?

There is no jQuery in the project, we can actually remove that file

**Comment by RealDebugg** [comment]
> 
> 
> Couldn't find the solution since I am not that good at HTML, CSS or JS. But it's diffently something todo with overlapping. All the sounds plays, there's a cursor. Even when the hack fails (Which it does since I can't see) I get the notification "Hack Failed" so yeah not sure what's causing this.

I'll send a pr here in a few, its a simple css error

**Comment by TaaVetP** [comment]
Well done people who did something to help this project be fixed
![image](https://user-images.githubusercontent.com/81780337/120434697-7707d200-c385-11eb-8389-4453f51e779b.png)

**Comment by RealDebugg** [comment]
:D working on another issue which should be out soon

**Comment by TaaVetP** [comment]
the answer going to f8 or that it is not possible to finish, it fails always even if correct

**Comment by RealDebugg** [comment]
Already reported and currently being worked on

**Comment by Jesper-Hustad** [comment]
Closing this issue now as this has been resolved.  
If you find new problems add it as an issue.
